### ISSUE TITLE
Feature request: Allow  extenstion through css prop

### ISSUE THREAD

**Issue by TxHawks** [johanholmerin/style9-jsx-prop#3]
It is pretty common to want to build basic components, that can later be extended with additional styles in much of the same way that it is often done in `styled` style APIs, and it could be nice to be able to do it using the `css` prop as well:

A possible way of going about it could be the one used by [@twind/macro](/tw-in-js/twind-jsx-preprocessor/blob/main/packages/macro/README.md).

```jsx
export default function Button({ className, ...props }) {
  return (
    <button
      type="button"
      css={{
        backgroundColor: 'red',
        color: '#fff',
      }}
      className={className}
      {...props}
    />
  )
}

<Button>Default white Text</Button>
<Button css={{ color: 'hotpink' }}>Pink text</Button>
```

With this pattern, it should be possible to merge `className`s created by the internal and external `css` props in a similar way to how `style9(style1.ineternal, style2.external)` works.

**Comment by johanholmerin** [comment]
To merge styles, style9 needs a generated object, i.e. `style1.ineternal`. This plugin does not keep the generated object, it generates a className string at compile time. There is also the issue of dynamic values being set as style-attributes.

If you have a proposal for an alternative API, or a PR, I would be happy to look at it.
